plugins { id 'com.android.application' }

android {
    namespace 'com.wallah.app'
    compileSdk 35
    defaultConfig {
        applicationId 'com.wallah.app'
        minSdk 24
        targetSdk 35
        versionCode 5
        versionName '1.0.4'
    }
    flavorDimensions 'role'
    productFlavors {
        customer {
            dimension 'role'
            applicationId 'com.wallah.customer'
            resValue 'string', 'app_name', 'ولعه - العميل'
            buildConfigField 'String', 'HOME_URL', '"https://wellah-production.up.railway.app/customer"'
        }
        admin {
            dimension 'role'
            applicationId 'com.wallah.management'
            resValue 'string', 'app_name', 'ولعه - الإدارة'
            buildConfigField 'String', 'HOME_URL', '"https://wellah-production.up.railway.app/admin"'
        }
        driver {
            dimension 'role'
            applicationId 'com.wallah.courier'
            resValue 'string', 'app_name', 'ولعه - الطيار'
            buildConfigField 'String', 'HOME_URL', '"https://wellah-production.up.railway.app/driver"'
        }
    }
    buildTypes { debug { applicationIdSuffix '.debug' } }
    buildFeatures { buildConfig true }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
